Wikia/mediawiki

- RELEASE-NOTES-1.33
- includes/specials/SpecialContributions.php
- includes/specials/pagers/ContribsPager.php
- languages/i18n/en.json
- languages/i18n/qqq.json
- tests/phpunit/includes/specials/ContribsPagerTest.php
Backport a set of upstream patches to improve ContribsPager query performance:
* https://gerrit.wikimedia.org/r/c/mediawiki/core/+/505814 and https://gerrit.wikimedia.org/r/c/mediawiki/core/+/504021  to address [T221380](https://phabricator.wikimedia.org/T221380) and [T220991](https://phabricator.wikimedia.org/T220991) by ensuring that ContribsPager uses denormalized timestamp and ID fields for ordering and pagination.
* https://gerrit.wikimedia.org/r/c/mediawiki/core/+/598887 to remove index forcing on `user_timestamp` in ContribsPager that forces the query planner into a suboptimal execution path on wikis where actor migration isn't reading the new schema.
* https://gerrit.wikimedia.org/r/c/mediawiki/core/+/551909 to allow limiting concurrent access to Contributions via PoolCounter.
> MAIN-20976 | Backport ContribsPager query optimization patches

- includes/parser/Parser.php
Currently `Parser` allows only hot linking images with `.jpg|.jpeg|.png|.gif` in the end of url. As we use revision, version and query params in our Vignette urls, they would not be allowed for render even if domain was added to `wgAllowExternalImagesFrom`. `ParserAllowExternalImage` hook will be used only if domain in image url is added to `wgAllowExternalImagesFrom` list or `wgAllowExternalImages` is set to `true`.
> PLATFORM-4871 | Add ParserAllowExternalImage hook in Parser::maybeMakeExternalImage method

- includes/registration/ExtensionRegistry.php
Use a global APCu cache key for the ExtensionRegistry queue to allow reusing the
cache between wikis that use the same set of extensions, instead of having
separate cache keys per wiki. The cache key already varies on the hash of the
list of extensions enqueued for loading.
> ExtensionRegistry: Use a global cache key for the queue

- includes/user/User.php
* https://wikia-inc.atlassian.net/browse/PLATFORM-5269
Hooks allows to modify cache options, before user is loaded. This can be used to pass additional `checkKeys`, which will refresh user if those changed.
@Wikia/core-platform-team
> PLATFORM-5269 | Add UserLoadFromCache Hook to User::loadFromCache

- includes/cache/MessageCache.php
Workaround T193271 performance regression by letting extensions signal that a
particular message key cannot exist in the DB. This allows us to use a
MessageCache::get hook handler to dynamically handle problematic keys in one
place (MessageCachePerformance extension) without patching core, while
maintaining compatibility with conditional message lookups that trigger fallback
logic depending on the outcome of a Message::exists() existence check.
> MessageCache: Let extensions signal that a particular key cannot exist in DB

- includes/user/User.php
Hitting the shared cluster in this hook can cause some overload, as we're not expected to create actors in this part of the code. which means we could be querying for the same actor all over again.
I think the default MediaWiki behaviour (just checking the local cluster copy) is fine here.
> Remove obsolete actor sync hook

- includes/Category.php
- includes/deferred/LinksDeletionUpdate.php
Add new Category::refreshCountsIfSmall() method that will do a non-locking
SELECT with LIMIT before deciding whether to do a full locking SELECT and
refresh. Call this from LinksDeletionUpdate.
Bug: T18036
Change-Id: I9de8311565988453b8e29a7f3d95d758182fcec1
> PLATFORM-6111 | Reinstate small category refresh logic in LinksDeletionUpdate

- includes/page/WikiPage.php
- tests/phpunit/includes/page/ArticleViewTest.php
WikiPage::getContentModel() gets called several times per request via
Action::getActionName(), triggering memcached I/O on each call - making it the single most requested key class at 15K rq/s. Excimer icicle graphs for index.php indicate about ~1% of time is spent in this method, so
let's add process caching to avoid redundant memcached fetches on subsequent
invocations.
Change-Id: Icdb9ffb849a0a0a264083957431495f8f4fb783e
> WikiPage: Add process cache for content model

- includes/deferred/LinksUpdate.php
- includes/jobqueue/jobs/CategoryMembershipChangeJob.php
- includes/jobqueue/jobs/ClearUserWatchlistJob.php
- includes/user/UserGroupMembership.php
https://fandom.atlassian.net/browse/SITE-945
https://github.com/wikimedia/mediawiki/commit/d4cb1968c844fcd4e29e6ba40751f6639dca0e53
https://kibana.wikia-inc.com/goto/8e18151becbb58c4523ebb8526dda7a1
Per conversation with @mszabo-wikia, let's check if the issue described in the ticket is a result of the simultaneous edits from pages with the same page_id from different wikis. If not, we'll at least get rid of some deadlocks
@Wikia/site-experience 
@Wikia/core-platform-team
> Reduce contention of getScopedLockAndFlush() callers by using the DB domain in the key

- .gitmodules
https://gerrit.wikimedia.org/r/c/mediawiki/extensions/ReplaceText/+/725053
https://fandom.atlassian.net/browse/PLATFORM-6360
This ports a security fix to ReplaceText from 1.31 onto 1.33. This fix is included from 1.35 onwards, so the fork can be discarded afterward.
> PLATFORM-6360 Backport T725053 fix to ReplaceText

- includes/cache/MessageCache.php
- includes/parser/Parser.php
- includes/parser/Sanitizer.php
- includes/user/User.php
We've made various backports and customizations to MW 1.33, some of which are still relevant in 1.37. This patch starts off a fresh clone of upstream's REL1_37 branch (REL1_37-Fandom), and cherry-picks select changes on top of it:
* https://github.com/Wikia/mediawiki/pull/19
* f900f0d28a353a049f3dda6386dad4b769be8c5d
* d2a8252524ed8f162aa604b6ea117a42cfd838c2
* e7282d7b882c6873597be73b12545e7872a1b829
Notably, we have some patches that I have not applied yet, because I feel we should have a conversation about them first—they might not be relevant any more. Specifically:
* https://github.com/Wikia/mediawiki/pull/9 - this technically works, but RC is unusably slow at such volume. I'd recommend reconsidering.
* https://github.com/Wikia/mediawiki/pull/18, …
> Apply our 1.33 customizations onto 1.37

- includes/parser/BlockLevelPass.php
- includes/parser/Sanitizer.php
- tests/parser/ParserTestParserHook.php
Our PortableInfobox extension uses the HTML5 <aside> tag in its generated HTML.
This tag isn't recognized as a block element (in the way e.g. <div> is) by the
legacy parser, resulting in some spurious empty paragraphs in the output.
As a fix, make the legacy parser aware of <aside> tags to avoid unnecessary
p-wrapping. Also add <aside> to the Sanitizer's internal attribute check.
I3e57f55ac69d2c1ee8a1d41c21b692e56fc7e628 takes care of updating Parsoid-PHP
accordingly.
Bug: T278565
Change-Id: I89dbdf7770e13e1b62320228a366c64e64217b0b
> Don't p-wrap <aside> tags in extension HTML

- includes/ActorMigration.php
* https://fandom.atlassian.net/browse/PLATFORM-6677
If multiple inserts happen at the same time, there are situations where upserting to new revision_actor_temp can cause deadlock. ActorMigration::getInsertValuesWithTempTable `pk` values are always autoincremented and there should not be cases where upsert is needed.
In one place where the function is used RevisionStore::insertRevisionRowOn, there is a similar function for comment on which insert is used as well.
@Wikia/platform-team @mszabo-wikia
> PLATFORM-6677 | Fix revision_actor_temp locking on new revision creation

- includes/Rest/EntryPoint.php
- includes/Rest/Reporter/ErrorReporter.php
- includes/Rest/Reporter/MWErrorReporter.php
- includes/Rest/Reporter/PHPErrorReporter.php
- includes/Rest/ResponseFactory.php
- includes/Rest/Router.php
- tests/phpunit/includes/Rest/EntryPointTest.php
- tests/phpunit/unit/includes/Rest/BasicAccess/MWBasicRequestAuthorizerTest.php
- tests/phpunit/unit/includes/Rest/ResponseFactoryTest.php
- tests/phpunit/unit/includes/Rest/RouterTest.php
- tests/phpunit/unit/includes/Rest/testRoutes.json
MW's REST API, as of the 1.37 release, will gracefully convert `HttpException`s to error responses but will let any other exception bubble up to MW's standard error handler that will then render a fully fledged and skinned HTML error page—something not really expected in an API context. Given that some of the handlers we're going to be shipping in 1.37 can and will throw such exceptions (e.g. Parsoid's routes will throw `ValidationException`s on invalid user-supplied parameters), let's be prudent and backport some proper error handling here.
> Backport fix for T285984 for graceful error handling in REST routes

- languages/Language.php
MediaWiki only supports 14 character timestamps, and most date input
fields accordingly limit the accepted input range to fit within that
constraint, so the largest acceptable date is 9999-12-31 23:59:59.
However, if an user's own timezone preference is set to a timezone with
a higher offset than the server timezone, such dates may overflow into
the year 10000 and cause an error ("The timestamp XYZ should have 14
characters"). This very commonly happens when an admin decides to block
an user until 9999-12-31 instead of using the infinite expiry for some
reason, effectively breaking the block log for every user with a
timezone offset higher than the server offset.
Making MediaWiki support dates beyond the year 10000 would be a larger
undertaking, so for now, limit the impact of this …
> Language: Don't generate local dates in the year 10000

- includes/EditPage.php
- includes/actions/McrUndoAction.php
https://fandom.atlassian.net/browse/PLATFORM-6588
Both traditional action=edit&undo= and the newer
action=mcrundo/action=mcrrestore endpoints suffer from a flaw that
allows for leaking entire private wikis by enumerating through revision
IDs when at least one page was publicly accessible via $wgWhitelistRead.
This is CVE-2021-44858.
05f06286f4def removed the restriction that user-supplied undo IDs belong
ot the same page, and was then copied into mcrundo. This check has been
restored by using RevisionLookup::getRevisionByTitle(), which returns
null if the revid is on a different page. This will break the workflow
outlined in T58184, but that could be restored in the future with better
access control checks.
action=mcrundo/action=restore suffer from an additional flaw that allows
for …
> PLATFORM-6588 SECURITY: Fix permissions checks in undo actions

- maintenance/update.php
purgeCache() invalidates the global check key for MessageBlobStore,
which results in MessageBlobStore being emptied every minute due to
wiki creations or site-wide update.php runs. Disable it while we consult
with upstream on the best way forward.
> CATS-3063 | Disable post-update cache invalidation

- includes/MediaWiki.php
initializeArticle() calls Title::getContentModel() before the WikiPage
object for the current page has been initialized, which results in a
redundant query to the page table as WikiPage hasn't yet seeded
LinkCache with data for the current page. Instead, use
WikiPage::getContentHandler(), which simply triggers WikiPage
initialization a bit earlier and eliminates the redundant query.
Bug: T206498
Change-Id: I2bd8000b9b67a54ad194fa6aca86be3c6039c8be
> MediaWiki: Avoid spurious page query

- includes/specials/SpecialListRedirects.php
Backport patch for https://phabricator.wikimedia.org/T279840.
> SITE-2630: Ignore pages that can't exist on Special:ListRedirects

- includes/api/ApiQueryRevisionsBase.php
Given $params = [ 'diffto' => 'prev' ];, $params['diffto'] != 0 is true on PHP 8 and false on PHP 7.3.[1] Fix the logic to also check whether diffto is numeric before treating it as a revision ID.
---
[1] https://onlinephp.io/c/81e7b
> ApiQueryRevisionsBase: Fix non-numeric diffto param handling on PHP 8

- includes/export/WikiExporter.php
Before PHP8, the operation evaluates to zero; from PHP8, TypeError is raised
Bug: T296545
Change-Id: Ibdbf431fe7adb3cc3150aaf87d69b5989a1f0ac3
> WikiExporter: Avoid bitwise op with non-integer

- includes/parser/Parser.php
- tests/phpunit/includes/api/query/ApiQueryRevisionsTest.php
PHP 8.0 changed the behavior of numeric comparisons such that non-numeric strings no longer weakly equal 0.[1] This breaks the logic in Parser::extractSections(), which was relying on the old comparison behavior for section indexes and in turn causes the revisions API to return a bogus 'nosuchsection' for error when called with rvsection=new.
Fix the logic by explicitly casting the section index to a number, which will yield the appropriate numeric section index for a numbered section index and 0 for a non-numeric section index (like 'new'). Also add test cases for the relevant API module.
--
[1] https://wiki.php.net/rfc/string_to_number_comparison
Change-Id: If32aa4d575cff66bd4eee56f9e3b0b0d9ba04fde
Bug: T323373
> Parser: Fix extractSections() behavior for PHP >= 8.0

- includes/GlobalFunctions.php
Reverts Wikia/mediawiki#68. This caused a regression for page names that contain a `?` and is probably the wrong place to resolve the original issue to start with.
> Revert "CATS-3647 Excluded special chars from url before link encode"

- includes/export/XmlDumpWriter.php
- tests/phpunit/includes/ExportTest.php
rel: https://gerrit.wikimedia.org/r/c/885444
In fdc3e9f9524d91a492bdc212486d4518991c0fe2, the code generating XML dumps was updated to support multi-content revisions. This refactor included a workaround for content types that are subclasses of TextContent to use getNativeData() rather than serialize(), apparently to satisfy the Flow extension.
However, this assumes that getNativeData() always returns a string. As demonstrated in T155582, this is not the case, which is one of the reasons why the method was deprecated. Notably, if a wiki has a custom content type defined whose getNativeData() returns a non-string value, and has pages using that content type, this breaks XML dump generation (dumpBackup.php) for that wiki and also makes those pages unexportable via Special:Export.
Fix it by …
> PLATFORM-8072| cherry-pick: Fix XML dumps for content types with non-string getNativeData() [REL1_37]

- maintenance/migrateRevisionActorTemp.php
Sorting of the original query is not very optimized and is very slow to run because is done by the rev_id which besides unique index don't have other indexes that would optimize this query. `revactor_rev` has proper index that allows sorting by it. Therefore, reversing the query makes on DB like Marvel the process ~6x quicker and is probably even more significant for larger Databases.
Original code result:
```
Completed merge of revision_actor into the revision table, 10000 rows updated.
real    1m18.585s
user    0m2.647s
sys     0m0.757s
```
Code with the reversed query:
```
Completed merge of revision_actor into the revision table, 10000 rows updated.
real    0m15.776s
user    0m2.228s
sys     0m1.153s
```
> Reverse the query in migrateRevisionActorTemp.php

- includes/changes/RCCacheEntryFactory.php
For anonymous users, the user ID is always zero, so it is possible for cached user links to be reused for different anonymous users after baf5c0a3b07603227d4498fba7898380ed911eda. This is not what we want, so use the user name as the cache key instead, which should be unique for both anonymous and registered users.
> MAIN-28662 | Vary RC user(talk) link cache on user name rather than ID

- includes/changes/ChangesList.php
- includes/changes/RCCacheEntryFactory.php
Rendering UserLinks or Tags, requires parsing which when run on thousands of records, adds up to significant amount of processing time. More often then not, this can be optimized by storing already visited tags or user links as those "renders" will not change for the single request run but are repeated constantly on the list.
@Wikia/platform-team @mszabo-wikia
> PLATFORM-8338 | Add additional caching to the ChangeList rendering

- languages/i18n/en.json
- languages/i18n/qqq.json
- resources/Resources.php
- resources/src/mediawiki.rcfilters/styles/mw.rcfilters.ui.SaveFiltersPopupButtonWidget.less
- resources/src/mediawiki.rcfilters/ui/SaveFiltersPopupButtonWidget.js
* https://fandom.atlassian.net/browse/PLATFORM-8107
* https://phabricator.wikimedia.org/T217304
* https://phabricator.wikimedia.org/T312169
Currently, if the popup will go outside the view, on scroll will go blank and also will stretch indefinitely. Bigger starting width seems to fix the issue, as the main reasons for the problem to occur is that our buttons are too big for the popup and therefore is calculated wrong.
@Wikia/wiki-platform
> PLATFORM-8107 | Fix RC filter bookmark popup rendering

- includes/registration/ExtensionRegistry.php
We should check for the warnings information from the result of ExtensionRegistry::readFromQueue, therefore pass whole data in the ExtensionRegistry::saveLazyAttributesToCache
> Pass proper data to ExtensionRegistry::saveLazyAttributesToCache to check warnings

- includes/skins/SkinTemplate.php
Fix that allows to have user page as a Main Page for a wiki. Currently it crashes since this case was not taken into account.
> PLATFORM-8453| user page as a main page

- includes/WebRequest.php
- tests/phpunit/includes/WebRequestTest.php
WebRequest::getFuzzyBool() will emit a deprecation warning on PHP 8.1 or newer if the parameter to be fetched is absent and the $default value is set to `true`, because strcasecmp() no longer accepts nulls. Fix it by returning out if the parameter is wholly absent and add a test for this scenario.
Bug: T351088
Change-Id: I85bbfec6aabef4e85859a76b6e50c80781024ae5
> WebRequest: Fix PHP 8.1 deprecations in getFuzzyBool()

- includes/Status.php
This is only used by ConfirmEdit and Phalanx to customize API error rendering for API edits. Let's declare the property explicitly to avoid errors on PHP 8.2. We can remove this if upstream fixes it later in a different way.
> Declare Status::apiHookResult

- includes/MediaWiki.php
Backport of https://github.com/wikimedia/mediawiki/commit/c8f582747454858743654cf3503990a2f1771b1f
> PLATFORM-9125 | Allow interwiki redirects on the same domain

- includes/parser/Sanitizer.php
In upstream MW 1.43, there was a [change](https://phabricator.wikimedia.org/T308160) allowing the `filter` in style.
This only affects Gamepedia wikis right now:
* When building UCP, we’ve introduced a branch in logic because Gamepedia wikis allowed var and Fandom did not (see: https://fandom.atlassian.net/browse/GPUCP-352).
* During this upgrade, Fandom branch in logic was not affected by MW 1.43.
We can safely change the Fandom branch in logic to allow `filter`, in MW 1.39 Upgrade we’ve allowed var on Fandom as we pulled in our MW contribution: https://phabricator.wikimedia.org/T288201, so I’d rather remove this branch in logic altogether. That will reduce unnecessary complexity and address the issue.
This reverts commit c47b14f9d4e925c3350d8c6722cfaf3095deada1 which introduces the …
> PLATFORM-10554 Remove diverging paths for CSS sanitization

- includes/MediaWikiServices.php
At Fandom MediawikiServices (along with HookContainer) is initialized early which prevents the lately added hook handlers to get registered. Reloading HookContainer should fix the issue for the time being.
Noticed for hook `MediaWikiServices`.
> Reload HookContainer service when MediawikiServices is reloaded

- includes/OutputTransform/Stages/DeduplicateStyles.php
- tests/phpunit/includes/OutputTransform/Stages/DeduplicateStylesTest.php
Why:
- DeduplicateStyles runs as a default post-cache output transformation for every backend pageview. It tokenizes the article HTML via Remex to deduplicate style nodes within.
- This is expensive for large pages. On the Barack Obama page, the transform takes 350+ ms on a parser cache hit.
- Some other transforms, like HandleSectionLinks, already use regexes to only run Remex-driven transforms on relevant elements to avoid a potentially expensive tokenization of the whole page.
What:
- Use a regular expression to limit this transform so that it only tokenizes potential <style> nodes. This takes ~2ms to execute on a large page[1], compared to ~166ms currently.
- Restrict this optimization to legacy parser output transformations, since the naïve regex used might otherwise match encoded …
> DeduplicateStyles: Only transform possible style nodes [backport]
